<a href="https://colab.research.google.com/github/JL-plusUltra/DataScience/blob/main/RawHouse_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
####csv and math packs###
import pandas as pd
import numpy as np
import random
from scipy.stats import iqr 
from scipy import stats

from geopy.geocoders import Nominatim
import pandas as pd

import folium
from folium.plugins import FastMarkerCluster

# importing necessary libraries
#import reverse_geocoder as rg
import pprint
 

#visual packs#
import matplotlib.pyplot as plt
import seaborn as sns


################Import Data#########################
data= pd.read_csv('/content/Raw_House_Data.csv')

In [ ]:
data = data.iloc[:, 1: ]

In [ ]:
#create z scores to elmininate outliers
data['z_score_sold']=stats.zscore(data['sold_price'])
data['z_score_bedroom']=stats.zscore(data['bedrooms'])
data['z_score_bathroom']=stats.zscore(data['bathrooms'])
data['z_score_sqft']=stats.zscore(data['sqrt_ft'])
data['z_score_fireplace']=stats.zscore(data['fireplaces'])

In [ ]:
#eliminate outliers beyond three standard deviations
data = data[(np.abs(stats.zscore(data['sold_price'])) < 3)]
data = data[(np.abs(stats.zscore(data['bathrooms'])) < 3)]
data = data[(np.abs(stats.zscore(data['bedrooms'])) < 3)]
data = data[(np.abs(stats.zscore(data['fireplaces'])) < 3)]
data = data[(np.abs(stats.zscore(data['sqrt_ft'])) < 3)]

          MLS  sold_price  ...  z_score_sqft  z_score_fireplace
51   21304804   1720000.0  ...      1.191512           2.737185
62   21808178   1295000.0  ...     -0.926956          -0.767309
74   21905469   1500000.0  ...      1.548628           0.984938
76   21731870   1700000.0  ...     -1.192549           0.108815
85   21506488   1400000.0  ...     -0.588683          -0.767309
91   21604114   1675000.0  ...      1.883311           2.737185
94   21204564   1600000.0  ...     -0.079927           2.737185
95   21317138   1680000.0  ...      1.541449           0.984938
99   21412375   1650000.0  ...      1.548628           0.984938
104  21601560   1500000.0  ...      1.401474           1.861062
107  21417996   1700000.0  ...      0.544576           0.984938
108  21422109   1650000.0  ...      1.692192           1.861062
109  21615519   1715000.0  ...      2.264654          -0.767309
110  21512252   1700000.0  ...      0.906178           0.984938
111  21202800   1500000.0  ...      1.905743          -0.767309

[15 rows x 21 columns]

In [ ]:
lats=data['latitude'].to_list()
lons=data['longitude'].to_list()
# Creating a zip with latitudes and longitudes
coords=list(zip(lats,lons))

In [ ]:
len(coords)

4766

In [ ]:
#build addresses for a map
from geopy.geocoders import Nominatim
geolocator = Nominatim(user_agent="test_app")  # enter a name for your app
full_address=[]
for i in range(len(coords)):
    location = geolocator.reverse(coords[i])
    address=location.raw['display_name']
    full_address.append(address)

In [ ]:
#add address to dataframe
add=pd.DataFrame(data=full_address , columns=['Address'])
add.head(10)

                                             Address
0  3715, North Old Sabino Canyon Road, Catalina F...
1  Foothills Court, Santa Cruz County, Arizona, U...
2  13774, North Old Ranch House Road, Marana, Pim...
3  North Spud Rock Place, Pima County, Arizona, 8...
4  Elm Ridge Circle, Catalina Foothills, Pima Cou...
5  1789, East Sahuaro Blossom Place, Catalina Foo...
6  The Gallery Golf Club, 14000, North Dove Mount...
7  5892, East Finisterra, Catalina Foothills, Pim...
8  13774, North Old Ranch House Road, Marana, Pim...
9  1439, East Desert Garden Drive, Catalina Footh...

In [ ]:
#concatonate address data to our house data
data['address'] = full_address

In [ ]:
#output our cleaned csv file
#data.to_csv('Final_House_Data.csv')

In [ ]:
#output to pdf